### ISSUE TITLE
Possible to output FEN into the board post

### ISSUE THREAD

**Issue by tens0rcat** [PetraOleum/vote-chess#1]
I'd like to be able to copy/paste into an analysis board.

**Comment by tens0rcat** [comment]
erm, maybe not.  Can't find an analysis board where stockfish isn't just a click away.  Then it's just engine v. engine. Both stockfish.  No point in that

**Comment by PetraOleum** [comment]
Yes, it's a tricky one - when I really need the FEN I just copy it out of the alt text field with inspect element
